### PR TITLE
feat: add support for MediatR 12

### LINKED ISSUE #17: v9.2 Incompatible with Mediatr v12 - changes to ServiceFactory
Changes in Mediatr v12 resolving ServiceFactory have impacted compatibility with this library v9.2.

I had a look, but admit I got lost in implementing the changes required to this library to attempt a PR.

From their repo:
https://github.com/jbogard/MediatR/wiki/Migration-Guide-11.x-to-12.0

Leveraging Microsoft.Extensions.DependencyInjection.Abstractions directly
The Mediator class now references IServiceProvider directly, instead of the previous custom delegate:

```
-    public Mediator(ServiceFactory serviceFactory) 
-        => _serviceFactory = serviceFactory;
+    public Mediator(IServiceProvider serviceProvider) 
+        : this(serviceProvider, new ForeachAwaitPublisher()) { }
+    public Mediator(IServiceProvider serviceProvider, INotificationPublisher publisher)
+    {
+        _serviceProvider = serviceProvider;
+        _publisher = publisher;
+    }
```
The ServiceFactory delegate was removed:

```c#
-public delegate object ServiceFactory(Type serviceType);
```
The functionality of MediatR.Extensions.DependencyInjection.Abstractions is now folded in directly to MediatR itself, so you can remove the reference to the extensions package and call the MediatR package directly:

```c#
services.AddMediatR(/* registration */);
```
For codebases not using the extension package, you may either implement IServiceProvider directly, or for many containers, they already directly support IServiceProvider directly.

### PR DESCRIPTION
**Pull request by alsami**
## Breaking changes

* Remove obsolete extension method to register `MediatR`. From now on you will require to use `builder.RegisterMediatR(MediatRConfiguration)` and provide a `MediatRConfiguration` using `MediatRConfigurationBuilder`.
* `MediatR` has been updated to version `12.0.0`. There are a set of breaking changes that you will need to fix. Please [follow the migration guide](https://github.com/jbogard/MediatR/wiki/Migration-Guide-11.x-to-12.0) for more details.

## Features

* Add support to register a custom implementation that implements all mediator interface (`IMediator`, `ISender`, `IPublisher`)
* Add support to register a custom implementation of `INotificationPublisher`
* Add support for `IRequestHandler<>` which is required for `MediatR` version `12.0.0`
* Add `ServiceProviderWrapper` that implements `IServiceProvider` and uses `ILifeTimeScope` to resolve services
* Add `ServiceProviderWrapper` to the container but only if `typeof(IServiceProvider)` has not been registered yet
* Re-add support for `netstandard2.0` to align with `MediatR`

Closes #17

### CODE REVIEW

**Comment by FixRM** [comment]
Hello @alsami. Can you please tell me the story behind IServiceProvider and why it was added? It looks like it doesn't play nice with https://github.com/ziyasal/Autofac.Extras.NLog. NLog.ILogger is always resolved as null if IServiceProvider is used. Or it must be the issue of Autofac itself?

**Comment by alsami** [comment]
Because MediatR is directly using it now instead of having a factory to define on how resolving dependencies work.

See here:
https://github.com/jbogard/MediatR/wiki/Migration-Guide-11.x-to-12.0#leveraging-microsoftextensionsdependencyinjectionabstractions-directly

Note that I also only add it when it has not been registered.

I am not sure why nlog is not able to resolve loggers with this change. I'd need to see how your dependencies are being registered and have a little bit more information about that before I can try to assist here.

**Comment by FixRM** [comment]
Thank you. Will MediatR still work if I register my own implementation of IServiceProvider?

Regarding Autofac.Extras.NLog, I tried to resolve ILogger with my own simple ServiceProvider implementation and got Autofac's "Not registered" exception. So I guess it's not your implementation fault, It must be something with scopes/ASP.NET integration. After all, constructor injection works as expected.

**Comment by alsami** [comment]
It will only register it, if it hasn't been registered yet.

I strongly advice against creating your own IServiceProvider, you are not up for that task, trust me.

**Comment by FixRM** [comment]
Man, your own ServiceProvider implementation is not rocket science, trust me)

**Comment by alsami** [comment]
> Man, your own ServiceProvider implementation is not rocket science, trust me)

Exactly, it's just a wrapper, not a service provider implementation.

**Pull request merged**
